### ISSUE TITLE
Adding Tox and Travis

### ISSUE THREAD

**Issue by jbpauly** [giswqs/pypackage#1]
@giswqs, I'm really enjoying using this repo and your updates to the original [pypackage cookiecutter](https://github.com/audreyfeldroy/cookiecutter-pypackage). If I want to include Tox and Travis functionality, similar to the original repo, would it work to just copy the `tox.ini` and `.travis.yml` files? Or do you have another recommendation? 

Thank you for sharing so much of your work online! The videos are fantastic and help a lot.

**Comment by giswqs** [comment]
@jbpauly Have you tried GitHub Actions? The package already has GitHub Actions integrated. You no longer need Travis CI. Take a look at the example below. 

https://github.com/giswqs/geodemo/tree/master/.github/workflows
https://github.com/giswqs/geodemo/actions

**Comment by giswqs** [comment]
Here are some video tutorials for using this package. 

1. [Creating a Python package with Cookiecutter Template](https://youtu.be/DAPAv9KbYZ0)
2. [Publishing Python packages on PyPI](https://youtu.be/7FcX9uWDuIQ)
3. [Deploying Python packages to PyPI using GitHub Actions](https://youtu.be/oayticDOZmU)
4. [Introduction to Python package file structure](https://youtu.be/0eLt_O6sIYU)

**Comment by jbpauly** [comment]
Oh AWESOME! I didn't know GitHub Actions replaces Travis CI in this instance. Super helpful and I will follow along with your videos. Thanks!

**Comment by giswqs** [comment]
@jbpauly Feel free to open new issues if you have any questions.
