### ISSUE TITLE
Docs not updating

### ISSUE THREAD

**Issue by josh-spatial** [giswqs/pypackage#4]
### Environment Information

-   Python version: 3.8
-   Operating System: macos M1 chip

### Description

I was following your YouTube videos for GeoSoft (which are great by the way), and I created my repo using pypackage.  But I for some reasons the docs and webpage are not updating.  I've corrected the branch to be `gh-pages` and use `/root` and that seemed to get the correct mkdocs-material page to load.  However, the index and version number do not match.  I believe it has to do with me using `main` instead of `master` for my default branch.  I noticed the edit buttons on the site refer to `master` urls.  But I'm not sure where to change this in the mkdocs configuration?  Here is my repo: https://github.com/josh-spatial/qdmap

**Comment by alicelovestocode** [comment]
Hi, I'm about to get this set up myself. I'm also using `main` for my default branch and wondering if I will encounter a similar problem. Were you able to resolve this issue?

**Comment by josh-spatial** [comment]
> 

Yes I was.  See the explanation at the `mkdocs-material` site [here](https://squidfunk.github.io/mkdocs-material/publishing-your-site/) regarding using main vs master branches for the github workflows.  I simply changed the branch to in the workflow.
